

text2output <- function(x) {
  paste0("Notes:", "\n", ifelse(x == "THMs", paste0(
    "SDWA1",
    "\n",
    "Sampling/Reporting Frequency:",
    "\n", {'\t'},
    "Sampled and reported Monthly.",
    "\n",
    "PWD/LIMS Parameters:",
    "\n", {'\t'},
    toString(c("Total THMs", "Bromoform","Bromodichloromethane", "Dibromochloromethane", "Chloroform")), 
    "\n",
    "PWD/LIMS Sites:",
    "\n", {'\t'},
    toString(dbp_sites),
    "\n",
    "Expected total samples: 80",
    "\n",
    "Sample Type:",
    "\n", {'\t'},
    "All samples are Sample Type D.",
    "\n",
    "Analysis Method:",
    "\n", {'\t'},
    "All samples should be analyzed with Method 221 (EPA 524.2 rev 4.1).",
    "\n",
    "Samples may be analyzed by contract labs or PWD labs."),
    ifelse(x == "Field-Chlorine Residual Total", paste0(
      "SDWA1",
      "\n",
      "Sampling/Reporting Frequency:",
      "\n", {'\t'},
      "Sample Frequency: Varies by site.",
      "\n",{'\t'},
      "Reporting Frequency: Monthly",
      "\n",
      "PWD/LIMS Parameters:",
      "\n", {'\t'},
      "Field-Chlorine Residual Total", 
      "\n",
      "PWD/LIMS Sites:",
      "\n", {'\t'},
      toString(drr_sites2),
      "\n",
      "Expected total samples: Varies",
      "\n",
      "Sample Type:",
      "\n", {'\t'},
      "All samples are Sample Type D.",
      "\n",
      "Analysis Method:",
      "\n", {'\t'},
      "All samples should be analyzed with Method 301 (Hach Method 10250, Hach Method 10260).",
      "\n",
      "Samples are historically analyzed in Field."), 
      ifelse(x == "Coliforms Total (Colilert)", paste0(
        "SDWA1",
        "\n",
        "Sampling/Reporting Frequency:",
        "\n", {'\t'},
        "Sample Frequency: Varies by site.",
        "\n",{'\t'},
        "Reporting Frequency: Monthly",
        "\n",
        "PWD/LIMS Parameters:",
        "\n", {'\t'},
        "Coliforms Total (Colilert)", 
        "\n",
        "PWD/LIMS Sites:",
        "\n", {'\t'},
        toString(drr_sites2),
        "\n",
        "Expected total samples: Varies",
        "\n",
        "Sample Type:",
        "\n", {'\t'},
        "All samples are Sample Type D.",
        "\n",
        "Analysis Method:",
        "\n", {'\t'},
        "All samples should be analyzed with Method 331 (ESM 9223 Colilert).",
        "\n",
        "Samples are historically analyzed by PWD Labs."),
        ifelse(x == "HAAs", paste0(
          "SDWA1",
          "\n",
          "Sampling/Reporting Frequency:",
          "\n", {'\t'},
          "Sampled and reported Monthly.",
          "\n",
          "PWD/LIMS Parameters:",
          "\n", {'\t'},
          "5 Haloacetic acids, Dibromoacetic acid, Dichloroacetic acid, Bromoacetic acid, Chloroacetic acid, Trichloroacetic acid", 
          "\n",
          "PWD/LIMS Sites:",
          "\n", {'\t'},
          toString(dbp_sites),
          "\n",
          "Expected total samples: 96",
          "\n",
          "Sample Type:",
          "\n", {'\t'},
          "All samples are Sample Type D.",
          "\n",
          "Analysis Method:",
          "\n", {'\t'},
          "All samples should be analyzed with Method 208 (SM 6251 B).",
          "\n",
          "Samples may be analyzed by contract labs or PWD labs."),
          ifelse(x == "Metals", paste0(
            "SDWA4",
            "\n",
            "Sampling/Reporting Frequency:",
            "\n", {'\t'},
            "Sampled and reported Quarterly on the first month of the quarter.",
            "\n",
            "PWD/LIMS Parameters:",
            "\n", {'\t'},
            "9 metals parameters are analyzed for Quarters 1-3:", 
            "\n", {'\t'}, {'\t'},
            "Arsenic, Antimony, Barium, Beryllium, Cadmium, Chromium, Nickel, Selenium, Thallium",
            "\n",{'\t'},
            "3 additional metals parameters are analyzed in Quarter 4:",
            "\n", {'\t'}, {'\t'},
            "Fluoride, Cyanide, Mercury",
            "\n",
            "PWD/LIMS Sites:",
            "\n", {'\t'},
            toString(hs_sites),
            "\n",
            "Expected total samples:",
            "\n", {'\t'},
            "Q1-Q3: 27",
            "\n", {'\t'},
            "Q4: 36",
            "\n",
            "Sample Type:",
            "\n", {'\t'},
            "Q1-Q3: All samples are Sample Type S except for Arsenic which is Sample Type E.",
            "\n", {'\t'},
            "Q4: All samples are Sample Type E.",
            "\n",
            "Analysis Method:",
            "\n", {'\t'},
            "Q1-Q3: All samples should be analyzed with Method 170 (EPA 200.8 rev 5.4)",
            "\n", {'\t'},
            "Q4:",
            "\n", {'\t'},{'\t'},
            "Method 170 (EPA 200.8 rev 5.4): Arsenic, Antimony, Barium, Beryllium, Cadmium, Chromium, Nickel, Selenium, Thallium, Mercury",
            "\n", {'\t'},{'\t'},
            "Method 107 (SM 4500-F-C): Fluoride",
            "\n", {'\t'},{'\t'},
            "Method 186 (Lachat 10-204-00-1X): Cyanide Total",
            "\n", {'\t'},{'\t'},
            "**Method 103 (SM 3112-B) could be used for Mercury if Mercury is analyzed by the contract lab.",
            "\n",
            "Samples may be analyzed by contract labs or PWD labs."),
            ifelse(x %in% c("Nitrite/Nitrate"), paste0(
              "SDWA4",
              "\n",
              "Sampling/Reporting Frequency:",
              "\n", {'\t'},
              "Sample Frequency: Monthly",
              "\n",{'\t'},
              "Reporting Frequency: Monthly",
              "\n",
              "PWD/LIMS Parameters:",
              "\n", {'\t'},
              "Nitrite/Nitrate", 
              "\n",
              "PWD/LIMS Sites:",
              "\n", {'\t'},
              toString(hs_sites),
              "\n",
              "Expected total samples: 3 per parameter(6 total)",
              "\n",
              "Sample Type:",
              "\n", {'\t'},
              "All samples are Sample Type E.",
              "\n",
              "Analysis Method:",
              "\n", {'\t'},
              "All samples should be analyzed with Method 120 (EPA 300.0 rev 2.1).",
              "\n",
              "Samples are historically analyzed by PWD Labs."),
              ifelse(x == "Orthophosphate & pH", paste0(
                "SDWA4",
                "\n",
                "Sampling/Reporting Frequency:",
                "\n", {'\t'},
                "Sample Frequency:",
                "\n",{'\t'},{'\t'},
                "Orthophosphate:",
                "\n",{'\t'},{'\t'},{'\t'},
                "Quarterly at:", toString(occt_sites),
                "\n",{'\t'},{'\t'},{'\t'},
                "Weekly at:", toString(hs_sites),
                "\n",{'\t'},{'\t'},
                "pH:",
                "\n",{'\t'},{'\t'},{'\t'},
                "Quarterly at:", toString(occt_sites),
                "\n",{'\t'},
                "Reporting Frequency:",
                "\n", {'\t'},{'\t'},
                "Orthophosphate:",
                "\n",{'\t'},{'\t'},{'\t'},
                "Quarterly for:", toString(occt_sites),
                "\n",{'\t'},{'\t'},{'\t'},
                "Monthly for:", toString(hs_sites),
                "\n",{'\t'},{'\t'},
                "pH:",
                "\n",{'\t'},{'\t'},{'\t'},
                "Quarterly for:", toString(occt_sites),
                "\n",
                "PWD/LIMS Parameters:",
                "\n", {'\t'},
                "Orthophosphate, pH", 
                "\n",
                "Expected total samples:",
                "\n",{'\t'},
                "Orthophosphate:",
                "\n",{'\t'},{'\t'},
                "High Service (Done Weekly): # of weeks in month multipied by 3",
                "\n",{'\t'},{'\t'},
                "Distribution (Done Quarterly): 12",
                "\n",{'\t'},
                "pH:",
                "\n",{'\t'},{'\t'},
                "Distribution (Done Quarterly): 12",
                "\n",
                "Sample Type:",
                "\n", {'\t'},
                "Samples taken from HS sites are Sample Type E",
                "\n", {'\t'},
                "Samples taken from OCCT sites are Sample Type D",
                "\n",
                "Analysis Method:",
                "\n", {'\t'},
                "Method 157 (SM 4500 P E): Orthophosphate",
                "\n", {'\t'},
                "Method 135 (SM 4500-H+ B, Hach Method 8156): pH",
                "\n",
                "Samples are historically analyzed by PWD Labs."),
                ifelse(x == "Secondaries", paste0(
                  "SDWA4",
                  "\n",
                  "Sampling/Reporting Frequency:",
                  "\n", {'\t'},
                  "Sampling Frequency:",
                  "\n",{'\t'},{'\t'},
                  "Chloride & Sulfate: Weekly",
                  "\n",{'\t'},{'\t'},
                  "Color: Monthly",
                  "\n",{'\t'},{'\t'},
                  "Iron & Manganese: Twice a month (not every other week)",
                  "\n",{'\t'},{'\t'},
                  "Silver: First month of Quarter",
                  "\n",{'\t'},{'\t'},
                  "Total Dissolved Solids: Apr - Nov (Monthly), Dec - Mar (Weekly)",
                  "\n", {'\t'},
                  "Reporting Frequency:",
                  "\n", {'\t'},{'\t'},
                  "Secondaries are reported in the month they were sampled",
                  "\n",
                  "PWD/LIMS Parameters:",
                  "\n", {'\t'},
                  toString(secondaries), 
                  "\n",
                  "PWD/LIMS Sites:",
                  "\n", {'\t'},
                  toString(hs_sites),
                  "\n",
                  "Expected total samples: Varies",
                  "\n",
                  "Sample Type:",
                  "\n", {'\t'},
                  "All samples are Sample Type S.",
                  "\n",
                  "Analysis Method:",
                  "\n", {'\t'},
                  "Method 120 (EPA 300.0 rev 2.1): Chloride, Sulfate",
                  "\n", {'\t'},
                  "Method 129 (SM 4500-H+ B): Color Apparent",
                  "\n", {'\t'},
                  "Method 139 (SM 2540 C): Solids Dissolved Total",
                  "\n", {'\t'},
                  "Method 169 (EPA 200.7 rev 4.4): Iron, Manganese",
                  "\n", {'\t'},
                  "Method 170 (EPA 200.8 rev 5.4): Silver",
                  "\n",
                  "Samples are historically analyzed by PWD labs.",
                  "\n",
                  "Secondaries are collected on Tuesdays"), 
                  ifelse(x %in% c("TOC", "TOC & Alkalinity"), paste0(
                    "SDWA1",
                    "\n",
                    "Sampling/Reporting Frequency:",
                    "\n", {'\t'},
                    "Sample Frequency: Weekly",
                    "\n",{'\t'},
                    "Reporting Frequency: Monthly",
                    "\n",
                    "PWD/LIMS Parameters:",
                    "\n", {'\t'},
                    "TOC, Alkalinity", 
                    "\n",
                    "PWD/LIMS Sites:",
                    "\n", {'\t'},
                    "Influent Sites: ",toString(river_sites),
                    "\n", {'\t'},
                    "Effluent Sites: ", toString(plant_sites)," 5502, and 6502 will not show up in reported data.",
                    "\n", {'\t'}, {'\t'},
                    "TOC Results must be reported in pairs of effluent and influent values. Effluents for Queen Lane (5501, 5502) and Belmont (6501, 6502) are averaged by the plant and reported using the LIMS number and site for the Northern Effluent (5501, 6501)",
                    "\n",
                    "Expected total samples: Varies",
                    "\n",
                    "Sample Type:",
                    "\n", {'\t'},
                    "Effluent samples are sample type P. Influent samples are sample type R.",
                    "\n",
                    "Analysis Method:",
                    "\n", {'\t'},
                    "Method 580 (SM 5310 B): TOC",
                    "\n", {'\t'},
                    "Method 584 (SM 2320 B-2011): Alkalinity",
                    "\n",
                    "Samples are historically analyzed by PWD Labs.",
                    "\n",
                    "Influent Samples are collected on Tuesdays, Effluent Samples are collected on Wednesdays."), 
                    ifelse(x == "Violation Check Samples", paste0(
                      "SDWA1",
                      "\n",
                      "Sampling/Reporting Frequency:",
                      "\n", {'\t'},
                      "Sampled and Reported only when there is a positive Coliform sample.",
                      "\n",
                      "PWD/LIMS Parameters:",
                      "\n", {'\t'},
                      "Coliforms Total (Colilert), E. coli (Colilert), Field-Chlorine Residual Total", 
                      "\n",
                      "PWD/LIMS Sites:",
                      "\n", {'\t'},
                      "Sites will include the site of the positive Coliform sample along with an upstream and downstream site.",
                      "\n",
                      "Expected total samples: Varies",
                      "\n",
                      "Sample Type:",
                      "\n", {'\t'},
                      "Field-Chlorine Residual Total: Always Sample Type D",
                      "\n", {'\t'},
                      "E. coli (Colilert):", 
                      "\n", {'\t'}, {'\t'},
                      "E. coli result from the Routine sample associated with positive Coliform is included with Sample Type D",
                      "\n", {'\t'}, {'\t'},
                      "E. coli results from Violation Check Sample are included with Sample Type C",
                      "\n", {'\t'},
                      "Coliforms Total (Colilert): Always Sample Type C. Only Violation Check Samples are included.  Positive Coliform result is reported with all other Coliform results for the month.",
                      "\n",
                      "Analysis Method:",
                      "\n", {'\t'},
                      "Method 301 (Hach Method 10250, Hach Method 10260): Field-Chlorine Residual Total",
                      "\n", {'\t'},
                      "Method 331 (SM 9223 Colilert): E. coli (Colilert), Coliforms Total (Colilert)",
                      "\n",
                      "Samples are historically analyzed by PWD labs."),
                      ifelse(x == "VOCs", paste0(
                        "SDWA4",
                        "\n",
                        "Sampling/Reporting Frequency:",
                        "\n", {'\t'},
                        "Sampled and reported Quarterly on second month of Quarter.",
                        "\n",
                        "PWD/LIMS Parameters:",
                        "\n", {'\t'},
                        toString(voc_params), 
                        "\n",
                        "PWD/LIMS Sites:",
                        "\n", {'\t'},
                        toString(hs_sites),
                        "\n", {'\t'},
                        "Xylenes are shown as two different species in LIMS but are reported as Xylenes Total.",
                        "\n",
                        "Expected total samples: 63",
                        "\n",
                        "Sample Type:",
                        "\n", {'\t'},
                        "All samples are Sample Type E.",
                        "\n",
                        "Analysis Method:",
                        "\n", {'\t'},
                        "Method 221 (EPA 524.2 rev 4.1)",
                        "\n",
                        "Samples may be analyzed by contract labs or PWD labs."),""
                      )
                      )
                    )
                  )
                )
              )
              
            )
          )
        )
      )
    )
  )
}